steps:
- name: 'gcr.io/cloud-builders/maven'
  args: ['package', '-DskipTests'] # Or 'install' if you need it in local Maven repo
  # Assuming your pom.xml is in the root of your source directory.

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/crackerapp:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/crackerapp:latest']

images:
- 'gcr.io/${PROJECT_ID}/crackerapp:latest'

options:
  logging: CLOUD_LOGGING_ONLY
