steps:
  # Step 1: Run Maven to build the JAR
  - name: 'gcr.io/cloud-builders/maven'
    args: ['clean', 'install']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/crackerbackend:latest', '.']

  # Step 3: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/crackerbackend:latest']

images:
  - 'gcr.io/${PROJECT_ID}/crackerbackend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
